source 'https://github.com/CocoaPods/Specs.git'

iphoneos_deployment_target = '11.0'
platform :ios, iphoneos_deployment_target

def shared_pods
  pod 'Alamofire'
end

inhibit_all_warnings!
use_modular_headers!

target 'DependenciesFromCocoapods' do
  shared_pods
end

post_install do |pi|
  pi.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      # to suppress xcode warnings at Pods project-file, overriding podspec's deployment target
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < iphoneos_deployment_target.to_f
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = iphoneos_deployment_target
      end
    end
  end
end
