source 'https://github.com/CocoaPods/Specs.git'

iphoneos_deployment_target = '11.0'
platform :ios, iphoneos_deployment_target

def shared_pods
  pod 'Alamofire'
  pod 'FLEX', '~> 3.1.2', :configurations => ['Debug', 'AdHoc']
end

inhibit_all_warnings!
use_modular_headers!

target 'Taxi' do
  shared_pods
end

target 'Yango' do
  shared_pods
end

target 'Lavka' do
  shared_pods
end

target 'MLUBV1' do
  shared_pods
end

target 'MLUBV2' do
  shared_pods
end

target 'YandexTaxiLike' do
  shared_pods
end

target 'MLUBVCore' do
  shared_pods
end

target 'TaxiCore' do
  shared_pods
end

post_install do |pi|
  pi.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      # to suppress xcode warnings at Pods project-file, overriding podspec's deployment target
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < iphoneos_deployment_target.to_f
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = iphoneos_deployment_target
      end
    end
  end
end
